server {
    listen 8080;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }

    location /api/ {
        proxy_pass https://cinetech-back-376228829130.europe-west1.run.app;
        proxy_set_header Host cinetech-back-376228829130.europe-west1.run.app;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_ssl_server_name on;
    }
}